name: Outdated Label Reset

on:
    pull_request:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    reset-label:
        runs-on: ubuntu-latest

        steps:
            -   name: Remove robot-regression-ui-e2e label
                uses: actions-ecosystem/action-remove-labels@v1
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    labels: 'robot-regression-ui-e2e'
